In [33]:
import numpy
import random
import pandas
data=pandas.read_csv('./Iris.csv')

In [ ]:
Q-1 Create a Numpy array of size 4 x 5.

In [27]:
nmparray = numpy.array([10, 12, 43, 64, 75])
matrix4x5 = numpy.array([nmparray, nmparray, nmparray, nmparray])
print(matrix4x5)

[[10 12 43 64 75]
 [10 12 43 64 75]
 [10 12 43 64 75]
 [10 12 43 64 75]]


In [ ]:
Q-2 Randomly initialize the array.

In [9]:
array = numpy.random.rand(3, 4)
print(array)

[[0.30911842 0.77414286 0.07961069 0.23948816]
 [0.52733213 0.79060711 0.63084163 0.960858  ]
 [0.83323335 0.74025863 0.97413659 0.77934169]]


In [ ]:
Q-3 Get the Transpose of the Matrix that you created. Create a square matrix and find its determinant.

In [17]:
nparray = numpy.array([[20, 9], [13, 34]])
print("Determinant of Matrix")
det = numpy.linalg.det(nparray)
print(int(det))
print("Transpose of Matrix")
print(nparray.T)

Determinant of Matrix
563
Transpose of Matrix
[[20 13]
 [ 9 34]]


In [ ]:
Q-4 Create another matrix of size 5 x 4 and randomly initialize it.

In [19]:
array = numpy.random.rand(5, 4)
print(array)

[[0.4941576  0.60275348 0.03119227 0.79472203]
 [0.96245708 0.32569347 0.4792826  0.5357047 ]
 [0.81089134 0.20530921 0.10089247 0.47369065]
 [0.00326972 0.23798522 0.808569   0.4528904 ]
 [0.30603145 0.47346192 0.87745409 0.79684401]]


In [ ]:
Q-5 Perform Matrix multiplication.

In [20]:
narray1 = numpy.array([[1, 2],[3, 4]])
narray2= numpy.array([[5, 6],[7, 8]])
npmatrix1 = numpy.array([narray1, narray1])
npmatrix2 = numpy.array([narray2, narray2])
product = numpy.dot(npmatrix2, npmatrix1)
print(product)

[[[[23 34]
   [23 34]]

  [[31 46]
   [31 46]]]


 [[[23 34]
   [23 34]]

  [[31 46]
   [31 46]]]]


In [ ]:
Q-6 Perform element wise matrix multiplication.

In [22]:
narray1 = numpy.array([[1, 2],[3, 4]])
narray2= numpy.array([[5, 6],[7, 8]])
npmatrix1 = numpy.array([narray1, narray1])
npmatrix2 = numpy.array([narray2, narray2])
product = numpy.multiply(npmatrix2, npmatrix1)
print(product)

[[[ 5 12]
  [21 32]]

 [[ 5 12]
  [21 32]]]


In [ ]:
Q-7 Find mean, median of the numpy array created.

In [23]:
narray = numpy.array([[1, 2],[3, 4]])
mean = numpy.mean(narray)
median = numpy.median(narray)
print("Mean of array", mean)
print("Median of array", median)

Mean of array 2.5
Median of array 2.5


In [ ]:
Q-8 Obtain each row in the second column of the first array.

In [28]:
print(matrix4x5[:,1])

[12 12 12 12]


In [ ]:
Q -9 Convert Numeric entries(columns) of Iris.csv to Mean Centered Version

In [34]:
datam = data.iloc[:,:]
datam.mean()

C:\Users\manan\AppData\Local\Temp/ipykernel_10080/992960010.py:2: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  datam.mean()


Id               75.500000
SepalLengthCm     5.843333
SepalWidthCm      3.054000
PetalLengthCm     3.758667
PetalWidthCm      1.198667
dtype: float64

In [ ]:
Q-10 Study about numpy array attributes and implement it on the first matrix.

In [37]:
matrix4x5.shape
brr = matrix4x5.shape
print(brr)

(10, 2)
