In [ ]:
Linear regression model from scratch

In [1]:
import numpy as np
import torch

In [2]:
inputs = np.array([[73, 67, 43],
[91, 88, 64],
[87, 134, 58],
[102, 43, 37],
[69, 96, 70]], dtype='float32')

In [3]:
targets = np.array([[56],
[81],
[119],
[22],
[103]], dtype='float32')

In [4]:
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

In [5]:
weight = torch.randn(2, 3, requires_grad=True)
bias = torch.randn(2, requires_grad=True)

In [6]:
inputs @ weight.t() + bias

tensor([[ 10.3572, -21.5407],
        [ 22.1317, -16.7742],
        [  8.3826, -47.5828],
        [  1.6569, -30.0957],
        [ 32.1263,  -2.8594]], grad_fn=<AddBackward0>)

In [7]:
def model(inputs):
    return inputs @ weight.t() + bias

In [8]:
prediction = model(inputs)
print(prediction)

tensor([[ 10.3572, -21.5407],
        [ 22.1317, -16.7742],
        [  8.3826, -47.5828],
        [  1.6569, -30.0957],
        [ 32.1263,  -2.8594]], grad_fn=<AddBackward0>)


In [ ]:
Loss function

In [10]:
diff0 = prediction - targets
torch.sum(diff0 * diff0) / diff0.numel()

tensor(8046.4243, grad_fn=<DivBackward0>)

In [11]:
def mse(t1, t2):
    diff = t1 - t2
    return torch.sum(diff * diff) / diff.numel()

In [12]:
loss = mse(prediction, targets)
print(loss)

tensor(8046.4243, grad_fn=<DivBackward0>)


In [ ]:
Compute gradients

In [13]:
loss.backward()
print(weight.grad)
print(bias.grad)

tensor([[-5055.5884, -6147.9688, -3571.9758],
        [-8333.7373, -9704.8145, -5718.2603]])
tensor([-61.2691, -99.9706])


In [ ]:
Train the model using gradient descent

In [14]:
with torch.no_grad():
    weight -= weight.grad * 1e-5
    bias -= bias.grad * 1e-5
    weight.grad.zero_()
    bias.grad.zero_()

In [15]:
prediction = model(inputs)
loss = mse(prediction, targets)
print(loss)

tensor(5565.3467, grad_fn=<DivBackward0>)


In [16]:
for i in range(100):
    prediction = model(inputs)
    loss = mse(prediction, targets)
    loss.backward()
    with torch.no_grad():
        weight -= weight.grad * 1e-5
        bias -= bias.grad * 1e-5
        weight.grad.zero_()
        bias.grad.zero_()

In [17]:
prediction = model(inputs)
loss = mse(prediction, targets)
print(loss)

tensor(161.7822, grad_fn=<DivBackward0>)


In [18]:
prediction

tensor([[ 59.9381,  59.7764],
        [ 88.3995,  90.9803],
        [100.1521,  94.5423],
        [ 37.3892,  36.7497],
        [103.2264, 108.0834]], grad_fn=<AddBackward0>)

In [19]:
targets

tensor([[ 56.],
        [ 81.],
        [119.],
        [ 22.],
        [103.]])