In [ ]:
Linear regression using PyTorch built-ins

In [ ]:
Define DataLoader

In [1]:
import numpy as np
import torch
# Targets (apples, oranges)
inputs = np.array([[73, 67, 43], 
                   [91, 88, 64], 
                   [87, 134, 58], 
                   [102, 43, 37], 
                   [69, 96, 70]], dtype='float32')
# Targets (apples, oranges)
targets = np.array([[56, 70], 
                    [81, 101], 
                    [119, 133], 
                    [22, 37], 
                    [103, 119]], dtype='float32')

inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)
from torch.utils.data import TensorDataset

In [2]:
train_ds = TensorDataset(inputs, targets)
train_ds[0:3]

(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.]]),
 tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.]]))

In [3]:
from torch.utils.data import DataLoader
batch_size = 5
train_dl = DataLoader(train_ds, batch_size, shuffle=True)

In [4]:
for xb, yb in train_dl:
    print(xb)
    print(yb)
    break

tensor([[ 69.,  96.,  70.],
        [ 73.,  67.,  43.],
        [102.,  43.,  37.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.]])
tensor([[103., 119.],
        [ 56.,  70.],
        [ 22.,  37.],
        [ 81., 101.],
        [119., 133.]])


In [ ]:
nn.Linear

In [5]:
import torch.nn as nn
model = nn.Linear(3, 2)
print(model.weight)
print(model.bias)

Parameter containing:
tensor([[-0.2657,  0.0201,  0.1813],
        [-0.1094, -0.4291, -0.2765]], requires_grad=True)
Parameter containing:
tensor([ 0.4006, -0.2237], requires_grad=True)


In [6]:
list(model.parameters())

[Parameter containing:
 tensor([[-0.2657,  0.0201,  0.1813],
         [-0.1094, -0.4291, -0.2765]], requires_grad=True),
 Parameter containing:
 tensor([ 0.4006, -0.2237], requires_grad=True)]

In [7]:
preds = model(inputs)
preds

tensor([[ -9.8539, -48.8417],
        [-10.4075, -65.6261],
        [ -9.5091, -83.2668],
        [-19.1283, -40.0568],
        [ -3.3142, -68.3116]], grad_fn=<AddmmBackward0>)

In [ ]:
loss functions

In [8]:
import torch.nn.functional as F
loss_fn = F.mse_loss
loss = loss_fn(model(inputs), targets)
print(loss)

tensor(17188.3242, grad_fn=<MseLossBackward0>)


In [ ]:
Optimizer

In [9]:
opt = torch.optim.SGD(model.parameters(), lr=1e-5)

In [ ]:
Train for multiple epochs

In [10]:
def fit(num_epochs, model, loss_fn, opt, train_dl):
    
    # Repeat for given number of epochs
    for epoch in range(num_epochs):
        
        # Train with batches of data
        for xb,yb in train_dl:
            
            # 1. Generate predictions
            pred = model(xb)
            
            # 2. Calculate loss
            loss = loss_fn(pred, yb)
            
            # 3. Compute gradients
            loss.backward()
            
            # 4. Update parameters using gradients
            opt.step()
            
            # 5. Reset the gradients to zero
            opt.zero_grad()
        
        # Print the progress
        if (epoch+1) % 10 == 0:
            print('Epoch [{}/{}], Loss: {:.4f}'.format(epoch+1, num_epochs, loss.item()))

In [11]:
fit(100, model, loss_fn, opt, train_dl)

Epoch [10/100], Loss: 936.1365
Epoch [20/100], Loss: 415.1145
Epoch [30/100], Loss: 359.9704
Epoch [40/100], Loss: 319.1625
Epoch [50/100], Loss: 283.3334
Epoch [60/100], Loss: 251.7425
Epoch [70/100], Loss: 223.8815
Epoch [80/100], Loss: 199.3061
Epoch [90/100], Loss: 177.6251
Epoch [100/100], Loss: 158.4935


In [12]:
prediction = model(inputs)
prediction

tensor([[ 60.2262,  75.0973],
        [ 83.1836,  99.7876],
        [111.5518, 127.2672],
        [ 38.3707,  64.6417],
        [ 93.6098, 101.4379]], grad_fn=<AddmmBackward0>)

In [13]:
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])

In [14]:
model(torch.tensor([[75, 63, 44.]]))

tensor([[57.8447, 73.2627]], grad_fn=<AddmmBackward0>)